#!/usr/bin/env python3

import sys
import time

from AD9833 import AD9833

# set the frequency in hz
#
# 2200 meters
# frequency = 137700
# 630 meters
# frequency = 472700
# 160 meters beacon
frequency = 1992000
# 20 meters
#frequency = 14010000

wpm = 10

# define Farnsworth timing
ditsperword = 50
secondsperdit = 60/(ditsperword*wpm)
dit = secondsperdit
dash = dit * 3
interelement = dit

# assume one interelement after each element
intercharacter = (interelement * 3) - interelement

# assume one intercharacter after each word
interword = (interelement * 7) - intercharacter

# operating conditions
print("frequency",frequency)
print("wpm",wpm)
print("seconds per dit",secondsperdit)
print("dit",dit)
print("dash",dash)
print("intercharacter",intercharacter)
print("interword",interword)

# a subset of the morse code table
morse = {
    "a": ".-",
    "b": "-...",
    "c": "-.-.",
    "d": "-..",
    "e": ".",
    "f": "..-.",
    "g": "--.",
    "h": "....",
    "i": "..",
    "j": ".---",
    "k": "-.-",
    "l": ".-..",
    "m": "--",
    "n": "-.",
    "o": "---",
    "p": ".--.",
    "q": "--.-",
    "r": ".-.",
    "s": "...",
    "t": "-",
    "u": "..-",
    "v": "...-",
    "w": ".--",
    "x": "-..-",
    "y": "-.--",
    "z": "--..",
    "1": ".----",
    "2": "..---",
    "3": "...--",
    "4": "....-",
    "5": ".....",
    "6": "-....",
    "7": "--...",
    "8": "---..",
    "9": "----.",
    "0": "-----"
}

# define the pins on the GPIO
data = 10
clk = 11
fsync = 8

# instantiate a AD9833 object
ad = AD9833(data,clk,fsync)

# start with everything off
ad.keyup()

# Morse code functions
#
# transmit a dit
def xdit(ad):
    ad.set_freq(frequency)
    time.sleep(dit)
    ad.keyup()
  
# transmit a dash
def xdash(ad):
    ad.set_freq(frequency)
    time.sleep(dash)
    ad.keyup()

# send a character
def send(ad,c):
    global morse
    c = c.lower()
    if c in morse:
        m = morse[c]
        for i in range(0,len(m)):
            if m[i] == ".":
                xdit(ad)
            else:
                xdash(ad)
            time.sleep(interelement)

# loop forever sending the "phrase"
#
phrase = "test beacon de ab2iu 1992khz FN32at generated by raspberry pi and ad9833"

xmit = 1
while xmit:
    for c in phrase:

        sys.stdout.write(c)
        sys.stdout.flush()

        if c == " ":
            time.sleep(interword)
        else:
            send(ad,c)
            time.sleep(intercharacter)
            
    # interword delay at end of line
    time.sleep(interword)

    sys.stdout.write("\n")
    sys.stdout.flush()
    # zero xmit to only transmit once
    #xmit = 0
    

# we normally never get here...
ad.keyup()
time.sleep(10)

    
